In [1]:
import pandas as pd
import random

# =========================
# 1. DATASET
# =========================

nombres = ["Juan", "Maria", "Carlos", "Ana", "Luis", "Pedro", "Sofia", "Elena"]
apellidos = ["Perez", "Gomez", "Lopez", "Ramirez", "Torres", "Diaz"]
roles = ["Profesor", "Trabajador"]
departamentos = ["Matematicas", "Ciencias", "Administracion", "Recursos Humanos", "Lenguaje"]

data = []

for i in range(200):
    nombre = random.choice(nombres) + " " + random.choice(apellidos)
    edad = random.randint(22, 65)
    rol = random.choice(roles)
    salario = random.randint(2500, 12000)
    departamento = random.choice(departamentos)
    años_exp = random.randint(1, 40)

    data.append([nombre, edad, rol, salario, departamento, años_exp])

df = pd.DataFrame(data, columns=[
    "Nombre", "Edad", "Rol", "Salario", "Departamento", "Años_Experiencia"
])

print("=== DATASET COMPLETO (primeras 10 filas) ===")
display(df.head(10))


# =========================
# 2. USO DE .loc
# =========================

print("\n=== SOLO PROFESORES ===")
display(df.loc[df["Rol"] == "Profesor"].head())

print("\n=== PERSONAS MAYORES DE 40 AÑOS ===")
display(df.loc[df["Edad"] > 40].head())

print("\n=== SOLO COLUMNAS NOMBRE Y SALARIO ===")
display(df.loc[:, ["Nombre", "Salario"]].head())

# Modificar un valor
df.loc[0, "Salario"] = 15000
print("\n=== FILA 0 MODIFICADA (.loc) ===")
display(df.loc[[0]])


# =========================
# 3. USO DE .iloc
# =========================

print("\n=== PRIMERAS 5 FILAS ===")
display(df.iloc[0:5])

print("\n=== FILAS 0-9 Y COLUMNAS 0-2 ===")
display(df.iloc[0:10, 0:3])

print("\n=== VALOR ESPECÍFICO (fila 0, columna 2) ===")
print(df.iloc[0, 2])

print("\n=== ÚLTIMAS 5 FILAS ===")
display(df.iloc[-5:])


# =========================
# 4. GUARDAR ARCHIVO
# =========================

df.to_csv("dataset_profesores_trabajadores.csv", index=False)

print("\nDataset guardado como 'dataset_profesores_trabajadores.csv'")

=== DATASET COMPLETO (primeras 10 filas) ===

         Nombre  Edad         Rol  Salario      Departamento  Años_Experiencia
0  Luis Ramirez    26    Profesor     9522    Administracion                20
1  Carlos Gomez    43  Trabajador     5951       Matematicas                25
2     Ana Lopez    24  Trabajador     3544  Recursos Humanos                 2
3    Sofia Diaz    50  Trabajador    11807          Lenguaje                31
4     Luis Diaz    51    Profesor    11810    Administracion                30
5  Pedro Torres    25    Profesor     2621          Lenguaje                26
6     Ana Perez    25    Profesor     9948       Matematicas                37
7    Maria Diaz    29    Profesor     6124  Recursos Humanos                28
8    Luis Lopez    31    Profesor     8497          Lenguaje                15
9   Pedro Gomez    26    Profesor     3527          Lenguaje                38

=== SOLO PROFESORES ===

         Nombre  Edad       Rol  Salario      Departamento  Años_Experiencia
0  Luis Ramirez    26  Profesor     9522    Administracion                20
4     Luis Diaz    51  Profesor    11810    Administracion                30
5  Pedro Torres    25  Profesor     2621          Lenguaje                26
6     Ana Perez    25  Profesor     9948       Matematicas                37
7    Maria Diaz    29  Profesor     6124  Recursos Humanos                28

=== PERSONAS MAYORES DE 40 AÑOS ===

          Nombre  Edad         Rol  Salario    Departamento  Años_Experiencia
1   Carlos Gomez    43  Trabajador     5951     Matematicas                25
3     Sofia Diaz    50  Trabajador    11807        Lenguaje                31
4      Luis Diaz    51    Profesor    11810  Administracion                30
10   Luis Torres    42  Trabajador    11002     Matematicas                23
11   Elena Perez    61    Profesor     4390        Lenguaje                10

=== SOLO COLUMNAS NOMBRE Y SALARIO ===

         Nombre  Salario
0  Luis Ramirez     9522
1  Carlos Gomez     5951
2     Ana Lopez     3544
3    Sofia Diaz    11807
4     Luis Diaz    11810

=== FILA 0 MODIFICADA (.loc) ===

         Nombre  Edad       Rol  Salario    Departamento  Años_Experiencia
0  Luis Ramirez    26  Profesor    15000  Administracion                20

=== PRIMERAS 5 FILAS ===

         Nombre  Edad         Rol  Salario      Departamento  Años_Experiencia
0  Luis Ramirez    26    Profesor    15000    Administracion                20
1  Carlos Gomez    43  Trabajador     5951       Matematicas                25
2     Ana Lopez    24  Trabajador     3544  Recursos Humanos                 2
3    Sofia Diaz    50  Trabajador    11807          Lenguaje                31
4     Luis Diaz    51    Profesor    11810    Administracion                30

=== FILAS 0-9 Y COLUMNAS 0-2 ===

         Nombre  Edad         Rol
0  Luis Ramirez    26    Profesor
1  Carlos Gomez    43  Trabajador
2     Ana Lopez    24  Trabajador
3    Sofia Diaz    50  Trabajador
4     Luis Diaz    51    Profesor
5  Pedro Torres    25    Profesor
6     Ana Perez    25    Profesor
7    Maria Diaz    29    Profesor
8    Luis Lopez    31    Profesor
9   Pedro Gomez    26    Profesor

=== VALOR ESPECÍFICO (fila 0, columna 2) ===
Profesor

=== ÚLTIMAS 5 FILAS ===

,Nombre,Edad,Rol,Salario,Departamento,Años_Experiencia
195,Luis Diaz,54,Profesor,10490,Recursos Humanos,10
196,Maria Ramirez,49,Profesor,8166,Recursos Humanos,16
197,Luis Lopez,36,Profesor,7145,Recursos Humanos,9
198,Carlos Perez,31,Profesor,7802,Lenguaje,2
199,Pedro Torres,48,Trabajador,7981,Lenguaje,30

Dataset guardado como 'dataset_profesores_trabajadores.csv'